---
root: true
env:
  node: true
extends:
  - "plugin:vue/recommended"
  - "@vue/eslint-config-typescript"
  - "@vue/eslint-config-prettier"
rules:
  no-console: warn
  no-unused-vars: warn
  vue/no-unused-components: warn
parserOptions:
  parser: "@typescript-eslint/parser"
overrides:
  - files:
      - "**/__tests__/*.{j,t}s?(x)"
    env:
      mocha: true

